### ISSUE TITLE
Install OKVIS with ROS Hydro

### ISSUE THREAD

**Issue by shanmo** [ethz-asl/okvis_ros#8]
Hi, 

My OS is ubuntu 12.04, 64 bit, with gcc 4.7.3, cmake 2.8.12.1
I am trying to install OKVIS with ROS Hydro, here is one error I encountered

Built target okvis_util
-- downloading...
     src='https://www.doc.ic.ac.uk/~sleutene/software/brisk-2.0.2.zip'
     dst='/home/catkin_ws/build/okvis_ros/okvis/brisk/src/brisk-2.0.2.zip'
     timeout='none'
CMake Error at brisk_external-stamp/download-brisk_external.cmake:22 (message):
  error: downloading
  'https://www.doc.ic.ac.uk/~sleutene/software/brisk-2.0.2.zip' failed

```
status_code: 1
status_string: "unsupported protocol"
log: libcurl was built with SSL disabled, https: not supported!
```

Could anybody help us on this issue?

**Comment by AlexisTM** [comment]
Dear, 

Your problem is libcurl which is not build for SSL protocol. 

You have two solution : Rebuild libcurl with SSL support or change https to http in the CMakeLists.txt of okvis.

https://github.com/ethz-asl/okvis/blob/master/CMakeLists.txt#L114

It should be in /home/catkin_ws/src/okvis_ros/okvis/CMakeLists.txt

You can, by the same opportunity, change every https of the okvis dependancies to http.

**Comment by shanmo** [comment]
I see, thanks! @AlexisTM
